server:
  port: 8080

spring:
  application:
    name: salon-backend

  datasource:
    url: jdbc:postgresql://postgres:5432/salon_app
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  web:
    cors:
      allowed-origins: "http://localhost:4200,http://frontend:4200"
      allowed-methods: "*"
      allowed-headers: "*"
      allow-credentials: true