server:
  port: 8080

# PostgreSQL Configuration (commented out for now)
#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/nailsalon
#    username: postgres
#    password: postgres
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
spring:
  application:
    name: salon-backend

# H2 Database Configuration
  datasource:
    url: jdbc:h2:mem:nailsalondb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000 # 24 hours in milliseconds